name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Criar arquivo .env
        run: |
          echo "CYPRESS_BASE_URL=https://www.saucedemo.com" >> .env
          echo "CYPRESS_username=standard_user" >> .env
          echo "CYPRESS_password=secret_sauce" >> .env
          echo "CYPRESS_TEXT_FIRST_NAME=Adejane" >> .env
          echo "CYPRESS_TEXT_LAST_NAME=Silva" >> .env
          echo "CYPRESS_TEXT_POSTAL_CODE=0000000" >> .env

      - name: Rodar testes Cypress
        run: npx cypress run

      - name: Upload de screenshots em caso de falha
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload de vídeos dos testes
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
